# Generated by Django 3.1.12 on 2021-09-21 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('words', djongo.models.fields.ArrayField(default=[], model_container=mainapp.models.Words, model_form_class=mainapp.models.WordForm)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
