# Generated by Django 3.2.7 on 2021-09-21 06:12

from django.db import migrations
import djongo.models.fields
import mainapp.forms
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='words',
            field=djongo.models.fields.ArrayField(default=[], model_container=mainapp.models.Words, model_form_class=mainapp.models.WordForm),
        ),
    ]
